AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-local-test


Globals:
  Function:
    Timeout: 600
    MemorySize: 2048

Resources:
  EtlDemoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: etl_demo/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get

